### ISSUE TITLE
07_TessellateGroundにmain.cppが無い

### ISSUE THREAD

**Issue by honyax** [techlabxe/d3d12_book_3#1]
honyaxと申します。初めまして。

07_TessellateGroundですが、main.cppが存在しないためコンパイルエラーになるようです。
06_TessellateTeapotのmain.cppをコピーしてきてクラス名だけ変えて実行は出来ましたが、branch作成の権限が無いらしく、プルリクは出せませんでした。

ご確認のほど、よろしくお願いいたします。

**Comment by techlabxe** [comment]
報告して頂き、ありがとうございます。
追加忘れをしていたようですので、追加してコミットを行いました。

**Comment by honyax** [comment]
ご対応、ありがとうございます。
正しくビルド、実行できることを確認しました。
Issueをクローズ致します。
